import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import mongoose from 'mongoose';
import Car from './models/Car.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '.env'), override: true });

const cars = [
  {
    name: 'Ghost Black Badge',
    brand: 'Rolls-Royce',
    model: 'Ghost',
    year: 2023,
    pricePerDay: 85000,
    images: ['https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 4,
    category: 'Luxury',
    description: 'The epitome of British luxury. Ghost Black Badge pushes the boundaries of craftsmanship with a 6.75L V12 twin-turbo engine.',
    features: ['6.75L V12 Twin-Turbo', 'Starlight Headliner', 'Bespoke Audio', 'Massage Seats', 'Night Vision'],
    rating: 5.0,
    totalReviews: 24,
    location: 'Mumbai, India',
    mileage: '10 km/l',
    color: 'Obsidian Black',
    availability: 'Available',
  },
  {
    name: 'RS7 Sportback',
    brand: 'Audi',
    model: 'RS7',
    year: 2023,
    pricePerDay: 22000,
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 5,
    category: 'Sports',
    description: 'Quattro all-wheel drive meets 4.0L V8 twin-turbo aggression in this sleek, high-performance fastback.',
    features: ['4.0L V8 Twin-Turbo', 'Quattro AWD', 'Matrix LED', 'Bang & Olufsen Audio', 'Air Suspension'],
    rating: 4.8,
    totalReviews: 38,
    location: 'Delhi, India',
    mileage: '12 km/l',
    color: 'Daytona Grey',
    availability: 'Available',
  },
  {
    name: 'M8 Competition',
    brand: 'BMW',
    model: 'M8',
    year: 2023,
    pricePerDay: 24000,
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 4,
    category: 'Sports',
    description: 'The BMW M8 Competition redefines what it means to drive fast in ultimate luxury. 625 hp of pure German engineering.',
    features: ['4.4L V8 M TwinPower', 'M xDrive AWD', 'Carbon Ceramic Brakes', 'Harman Kardon Audio', 'Active M Diff'],
    rating: 4.9,
    totalReviews: 31,
    location: 'Bangalore, India',
    mileage: '11 km/l',
    color: 'Frozen Dark Blue',
    availability: 'Available',
  },
  {
    name: 'Nexon EV Max',
    brand: 'Tata',
    model: 'Nexon EV',
    year: 2024,
    pricePerDay: 4500,
    images: ['https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80'],
    fuelType: 'Electric',
    transmission: 'Auto',
    seats: 5,
    category: 'SUV',
    description: 'India\'s best-selling electric SUV. 437 km range, fast charging, and a feature-rich cabin make it perfect for city drives.',
    features: ['40.5 kWh Battery', '437 km Range', 'DC Fast Charging', 'Panoramic Sunroof', 'Connected Car Tech'],
    rating: 4.5,
    totalReviews: 67,
    location: 'Pune, India',
    mileage: '0 (Electric)',
    color: 'Pristine White',
    availability: 'Available',
  },
  {
    name: 'Grand Vitara Alpha',
    brand: 'Suzuki',
    model: 'Grand Vitara',
    year: 2024,
    pricePerDay: 3800,
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80'],
    fuelType: 'Hybrid',
    transmission: 'Auto',
    seats: 5,
    category: 'SUV',
    description: 'Strong hybrid technology meets SUV practicality. Grand Vitara delivers an impressive 27.97 km/l fuel efficiency.',
    features: ['Strong Hybrid System', 'AllGrip AWD', 'Head-Up Display', 'Panoramic Sunroof', '360° Camera'],
    rating: 4.4,
    totalReviews: 52,
    location: 'Chennai, India',
    mileage: '28 km/l',
    color: 'Grandeur Grey',
    availability: 'Available',
  },
  {
    name: 'Huracán EVO',
    brand: 'Lamborghini',
    model: 'Huracán',
    year: 2023,
    pricePerDay: 55000,
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 2,
    category: 'Sports',
    description: 'Naturally aspirated V10 fury. The Huracán EVO is raw Italian passion engineered into 630 hp of screaming performance.',
    features: ['5.2L V10 N/A', 'Lamborghini Dinamica Veicolo', 'Carbon Ceramic Brakes', 'Launch Control', 'Scissor Doors'],
    rating: 5.0,
    totalReviews: 18,
    location: 'Mumbai, India',
    mileage: '8 km/l',
    color: 'Giallo Belenus',
    availability: 'Available',
  },
  {
    name: 'SF90 Stradale',
    brand: 'Ferrari',
    model: 'SF90',
    year: 2023,
    pricePerDay: 65000,
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80'],
    fuelType: 'Hybrid',
    transmission: 'Auto',
    seats: 2,
    category: 'Sports',
    description: 'Ferrari\'s most powerful road car ever. The SF90 Stradale combines a twin-turbo V8 with 3 electric motors for 986 hp.',
    features: ['986 hp Hybrid System', 'eManettino Drive Mode', '0-100 in 2.5s', 'Carbon Fibre Body', 'Retractable Hardtop'],
    rating: 5.0,
    totalReviews: 14,
    location: 'Delhi, India',
    mileage: '14 km/l',
    color: 'Rosso Corsa',
    availability: 'Available',
  },
  {
    name: '911 Turbo S',
    brand: 'Porsche',
    model: '911',
    year: 2023,
    pricePerDay: 38000,
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 4,
    category: 'Sports',
    description: 'The benchmark sports car. 650 hp, 0–100 in 2.7 seconds, and an iconic rear-engined layout that has thrilled drivers for 60 years.',
    features: ['3.8L Twin-Turbo Flat-6', 'PDK Transmission', 'PASM Sport Suspension', 'Sport Chrono Package', 'Bose Surround Sound'],
    rating: 4.9,
    totalReviews: 29,
    location: 'Hyderabad, India',
    mileage: '10 km/l',
    color: 'GT Silver',
    availability: 'Available',
  },
  {
    name: 'AMG GT 63 S',
    brand: 'Mercedes',
    model: 'AMG GT 63',
    year: 2023,
    pricePerDay: 30000,
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 4,
    category: 'Luxury',
    description: 'Four doors, four seats, and four-wheel drive to match 630 hp AMG fury. The GT 63 S is the world\'s most powerful 4-door AMG.',
    features: ['4.0L V8 Biturbo', 'AMG Performance 4MATIC+', 'AMG Ride Control+', 'Burmester 3D Audio', 'AMG TRACK PACE'],
    rating: 4.8,
    totalReviews: 22,
    location: 'Bangalore, India',
    mileage: '10 km/l',
    color: 'Selenite Grey Magno',
    availability: 'Available',
  },
  {
    name: 'Fortuner Legender',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2024,
    pricePerDay: 6500,
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80'],
    fuelType: 'Diesel',
    transmission: 'Auto',
    seats: 7,
    category: 'SUV',
    description: 'The legendary SUV that dominates every terrain. Fortuner Legender brings commanding presence and legendary reliability.',
    features: ['2.8L Diesel Engine', '4x4 Capability', 'Bi-Beam LED Headlamps', 'JBL Premium Audio', 'Toyota Safety Sense'],
    rating: 4.6,
    totalReviews: 83,
    location: 'Kolkata, India',
    mileage: '15 km/l',
    color: 'Attitude Black',
    availability: 'Available',
  },
  {
    name: 'XUV700 AX7',
    brand: 'Mahindra',
    model: 'XUV700',
    year: 2024,
    pricePerDay: 5200,
    images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80'],
    fuelType: 'Diesel',
    transmission: 'Auto',
    seats: 7,
    category: 'SUV',
    description: 'ADAS-loaded, turbo-diesel powerhouse. XUV700 AX7 sets a new benchmark for feature-per-rupee value in India.',
    features: ['ADAS Level 2', '2.2L mStallion Diesel', 'Sony 3D Sound', 'Panoramic Sunroof', 'Wireless Charging'],
    rating: 4.5,
    totalReviews: 91,
    location: 'Mumbai, India',
    mileage: '16 km/l',
    color: 'Red Rage',
    availability: 'Available',
  },
  {
    name: 'Phantom Series II',
    brand: 'Rolls-Royce',
    model: 'Phantom',
    year: 2024,
    pricePerDay: 120000,
    images: ['https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800&q=80'],
    fuelType: 'Petrol',
    transmission: 'Auto',
    seats: 4,
    category: 'Luxury',
    description: 'The Phantom is simply the greatest car in the world. Unmatched silence, supreme craftsmanship, and imperious presence.',
    features: ['6.75L Twin-Turbo V12', 'Gallery Dashboard', 'Flagbearer Suspension', 'Bespoke Audio', 'Night Vision Camera'],
    rating: 5.0,
    totalReviews: 9,
    location: 'Delhi, India',
    mileage: '9 km/l',
    color: 'Arctic White',
    availability: 'Available',
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected');

    await Car.deleteMany({});
    console.log('🗑️  Cleared existing cars');

    const inserted = await Car.insertMany(cars);
    console.log(`🚗 Inserted ${inserted.length} cars successfully:`);
    inserted.forEach(c => console.log(`   • ${c.brand} ${c.name} — ₹${c.pricePerDay}/day`));

    await mongoose.disconnect();
    console.log('\n✅ Database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
}

seed();
